language: android
dist: trusty

android:
  components:
    - extra-android-m2repository
    - extra-google-m2repository
    - extras-google-google_play_services
    - sys-img-armeabi-v7a-google_apis-25

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - ./gradlew app:build