language: android
dist: trusty

before_install:
  - chmod +x gradlew
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses

android:
  components:
    - android-28
    - build-tools 28.0.3
    - extra-android-m2repository
    - extra-google-m2repository
    - extras-google-google_play_services
    - sys-img-armeabi-v7a-google_apis-25

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - ./gradlew app:build