language: android
dist: trusty

before_install:
  - yes | sdkmanager "platforms;android-28"

android:
  components:
    - android-28
    - build-tools 28.0.3
    - extra-android-m2repository
    - extra-google-m2repository
    - extras-google-google_play_services
    - sys-img-armeabi-v7a-google_apis-25
    licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - ./gradlew app:build